main: me.cade.PluginSK.Main
name: PluginSK
version: 1.0
author: CadeHeinberg
api-version: '1.13'
depend: [ProtocolLib, XGlow]

commands:
  spawn:
  givekit:
  givekittoall:
  setunlocked:
  sendplayer:
  